apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8
  labels:
    app: spring-boot-k8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-k8
  template:
    metadata:
      labels:
        app: spring-boot-k8
    spec:
      containers:
        - name: spring-boot-k8
          image: kumaraakash25/springboot-k8:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080